import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createPool} from '../src/database.js';
import {buildApp} from '../src/app.js';
const databaseUrl=process.env.TEST_DATABASE_URL;
test('Boards persist isolated workplaces, panels, tasks, tags, moves, completion and archive', {skip:!databaseUrl}, async t=>{
 assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(databaseUrl).hostname));
 const pool=createPool(databaseUrl);
 for(const file of ['01-schema.sql','02-usernames.sql','08-profile-picture.sql','04-boards.sql'])await pool.query(await readFile(new URL(`../../postgres/init/${file}`,import.meta.url),'utf8'));
 const prefix=`boards-${randomUUID()}`;
 const app=await buildApp({pool,logger:false,origins:[],verifyIdToken:async token=>({uid:`${prefix}-${token}`,firebase:{sign_in_provider:'password'}})});
 t.after(async()=>{await pool.query('DELETE FROM public.users WHERE firebase_uid IN ($1,$2)',[`${prefix}-owner`,`${prefix}-other`]);await app.close();});
 const call=async(data,token='owner',status=200)=>{
  const r=await app.inject({method:'POST',url:'/boards',headers:{authorization:`Bearer ${token}`},payload:data});
  assert.equal(r.statusCode,status,r.body);return r.json();
 };
 assert.equal((await app.inject({method:'POST',url:'/boards',payload:{action:'listWorkplaces'}})).statusCode,401);
 const w=(await call({action:'createWorkplace',name:'Launch'})).workplace;
 const second=(await call({action:'createWorkplace',name:'Other'})).workplace;
 assert.equal((await call({action:'listWorkplaces'})).workplaces.length,2);
 assert.deepEqual((await call({action:'listWorkplaces'},'other')).workplaces,[]);
 for(const action of ['getBoard','renameWorkplace','deleteWorkplace','createTaskColumn','createOrgTask','deleteOrgTask','setTaskTags','reorderOrgTasks'])await call({action,workplaceId:w.id,name:'intrusion'},'other',404);
 const run=(action,data={},status=200)=>call({action,workplaceId:w.id,...data},'owner',status);
 await run('createTaskColumn',{name:'',color:'bad'},400);
 await run('createTaskColumn',{name:'Bad',color:'not-a-colour'},400);
 const a=(await run('createTaskColumn',{name:'To do'})).column;
 const b=(await run('createTaskColumn',{name:'Done',color:'#2E7D5B'})).column;
 const tag=(await run('createTaskTag',{name:'Priority',color:'#2563EB'})).tag;
 const task=(await run('createOrgTask',{columnId:a.id,title:'Write',description:'Details',tagIds:[tag.id],completed:true})).task;
 assert.equal(task.tags[0].id,tag.id);assert.equal(task.completed,true);
 await run('createOrgTask',{columnId:a.id,title:'No foreign tag',tagIds:[randomUUID()]},400);
 await call({action:'createOrgTask',workplaceId:second.id,columnId:a.id,title:'Invalid'},'owner',404);
 await call({action:'setTaskTags',workplaceId:second.id,taskId:task.id,tagIds:[]},'owner',404);
 await run('updateOrgTask',{taskId:task.id,completed:'yes'},400);
 await Promise.all([run('updateOrgTask',{taskId:task.id,title:'Updated'}),run('updateOrgTask',{taskId:task.id,description:'Concurrent description'})]);
 let board=await run('getBoard');assert.equal(board.tasks[0].title,'Updated');assert.equal(board.tasks[0].description,'Concurrent description');
 await run('reorderOrgTasks',{columnId:b.id,taskIds:[task.id]});
 board=await run('getBoard');assert.equal(board.tasks[0].column_id,b.id);
 await run('reorderOrgTasks',{columnId:b.id,taskIds:[]},409);
 await run('updateOrgTask',{taskId:task.id,archived:true});
 assert.equal((await run('listOrgTasks')).tasks.length,0);
 assert.equal((await run('listOrgTasks',{archived:true})).tasks.length,1);
 await run('reorderOrgTasks',{columnId:a.id,taskIds:[task.id]},400);
 await run('updateOrgTask',{taskId:task.id,archived:false,completed:false});
 await run('deleteTaskTag',{tagId:tag.id});
 assert.deepEqual((await run('getBoard')).tasks[0].tags,[]);
 await run('renameWorkplace',{name:'Renamed'});
 assert.equal((await call({action:'listWorkplaces'})).workplaces[0].name,'Renamed');
 const persisted=(await pool.query('SELECT board FROM public.board_workplaces WHERE id=$1',[w.id])).rows[0].board;
 assert.equal(persisted.tasks[0].column_id,b.id);assert.equal(persisted.tasks[0].completed,false);
 await run('updateOrgTask',{taskId:task.id,archived:true});
 await run('deleteTaskColumn',{columnId:b.id});assert.equal((await run('getBoard')).tasks.length,0);
 await run('deleteWorkplace');assert.equal((await call({action:'listWorkplaces'})).workplaces.length,1);
});
