import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createPool} from '../src/database.js';
import {buildApp} from '../src/app.js';

const databaseUrl=process.env.TEST_DATABASE_URL;
test('Gantt persists calendars, enforces ownership and validates dependencies and row ordering', {skip:!databaseUrl}, async t=>{
 const url=new URL(databaseUrl);
 assert.ok(['localhost','127.0.0.1','[::1]'].includes(url.hostname),'Integration test database must be local');
 const pool=createPool(databaseUrl);
 for(const file of ['01-schema.sql','02-usernames.sql','08-profile-picture.sql','03-gantt.sql'])await pool.query(await readFile(new URL(`../../postgres/init/${file}`,import.meta.url),'utf8'));
 const prefix=`gantt-test-${randomUUID()}`;
 const app=await buildApp({pool,logger:false,origins:['http://localhost:3000'],verifyIdToken:async token=>({uid:`${prefix}-${token}`,email:`${token}@example.test`,firebase:{sign_in_provider:'password'}})});
 t.after(async()=>{await pool.query('DELETE FROM public.users WHERE firebase_uid IN ($1,$2)',[`${prefix}-owner`,`${prefix}-other`]);await app.close();});
 const call=async(data,token='owner',expected=200)=>{
  const r=await app.inject({method:'POST',url:'/gantt',headers:{authorization:`Bearer ${token}`},payload:data});
  assert.equal(r.statusCode,expected,r.body);return r.json();
 };
 assert.equal((await app.inject({method:'POST',url:'/gantt',payload:{action:'listCalendars'}})).statusCode,401);
 const {calendar}=await call({action:'createCalendar',name:'Project A',color:'#2E7D5B'});
 const cal=calendar.id;
 const {calendar:second}=await call({action:'createCalendar',name:'Project B'});
 assert.equal((await call({action:'listCalendars'})).calendars.length,2);
 assert.deepEqual((await call({action:'listCalendars'},'other')).calendars,[]);
 for(const action of ['listItems','renameCalendar','deleteCalendar','saveItem','deleteItem','reorderItems'])await call({action,calendar_id:cal,name:'Stolen'},'other',404);
 const base={action:'saveItem',calendar_id:cal,kind:'task',title:'First',description:'Notes',start_date:'2026-09-01',end_date:'2026-09-05',completed:false};
 await call({...base,start_date:'2026-02-30'},'owner',400);
 await call({...base,end_date:'2026-08-31'},'owner',400);
 await call({...base,prerequisite_id:randomUUID()},'owner',400);
 await call(base);
 let items=(await call({action:'listItems',calendar_id:cal})).items;
 const first=items[0].id;
 assert.equal(items[0].start_date,'2026-09-01');assert.equal(items[0].description,'Notes');
 await call({...base,title:'Second',kind:'event',prerequisite_id:first});
 items=(await call({action:'listItems',calendar_id:cal})).items;const secondItem=items[1].id;
 await call({...base,item_id:first,prerequisite_id:secondItem},'owner',400);
 await call({...base,item_id:first,prerequisite_id:first},'owner',400);
 await call({...base,calendar_id:second.id,prerequisite_id:first},'owner',400);
 await call({...base,calendar_id:second.id,item_id:first},'owner',404);
 await call({...base,item_id:first,title:'Updated',completed:true});
 await call({action:'reorderItems',calendar_id:cal,item_ids:[secondItem,first]});
 items=(await call({action:'listItems',calendar_id:cal})).items;
 assert.deepEqual(items.map(i=>i.id),[secondItem,first]);assert.equal(items[0].prerequisite_kind,'event');assert.equal(items[1].completed,true);
 await call({action:'reorderItems',calendar_id:cal,item_ids:[first,first]},'owner',409);
 await call({action:'reorderItems',calendar_id:cal,item_ids:[first]},'owner',409);
 await call({action:'renameCalendar',calendar_id:cal,name:'Renamed'});
 assert.equal((await call({action:'listItems',calendar_id:cal})).items[0].calendar_name,'Renamed');
 await call({action:'deleteItem',calendar_id:cal,item_id:first});
 items=(await call({action:'listItems',calendar_id:cal})).items;assert.equal(items[0].prerequisite_id,null);
 await call({action:'deleteCalendar',calendar_id:cal});
 assert.equal((await pool.query('SELECT id FROM public.gantt_items WHERE calendar_id=$1',[cal])).rowCount,0);
 assert.equal((await call({action:'listCalendars'})).calendars.length,1);
});
