import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createPool} from '../src/database.js';
import {buildApp} from '../src/app.js';
const databaseUrl=process.env.TEST_DATABASE_URL;
test('Schedules persist weeks, isolate owners, validate blocks and delete nested data', {skip:!databaseUrl},async t=>{
 assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(databaseUrl).hostname));
 const pool=createPool(databaseUrl);
 for(const file of ['01-schema.sql','02-usernames.sql','08-profile-picture.sql','07-schedule.sql'])await pool.query(await readFile(new URL(`../../postgres/init/${file}`,import.meta.url),'utf8'));
 const prefix=`schedule-${randomUUID()}`;
 const app=await buildApp({pool,logger:false,origins:[],verifyIdToken:async token=>({uid:`${prefix}-${token}`,firebase:{sign_in_provider:'password'}})});
 t.after(async()=>{await pool.query('DELETE FROM public.users WHERE firebase_uid IN ($1,$2)',[`${prefix}-owner`,`${prefix}-other`]);await app.close();});
 const call=async(data,token='owner',status=200)=>{const r=await app.inject({method:'POST',url:'/schedule',headers:{authorization:`Bearer ${token}`},payload:data});assert.equal(r.statusCode,status,r.body);return r.json();};
 assert.equal((await app.inject({method:'POST',url:'/schedule',payload:{action:'getWeek'}})).statusCode,401);
 const week={action:'getWeek',startDate:'2026-09-28'};
 assert.deepEqual((await call(week)).groups,[]);
 const g=(await call({action:'createGroup',name:'Operations'})).group;
 const row=(await call({action:'createRow',groupId:g.id,name:'My schedule'})).row;
 const block={action:'saveBlock',rowId:row.id,date:'2026-09-30',title:'Morning',start:'09:00',end:'17:00',color:'#D97706',note:'Details'};
 for(const data of [{start:'25:00'},{end:'08:00'},{date:'2026-02-30'},{color:'invalid'},{title:''}])await call({...block,...data},'owner',400);
 const first=(await call(block)).block;
 await call({...block,date:'2026-10-05',title:'Next week'});
 assert.equal((await call(week)).blocks.length,1);
 assert.equal((await call({...week,startDate:'2026-10-05'})).blocks[0].title,'Next week');
 assert.deepEqual((await call(week,'other')).groups,[]);
 for(const data of [{action:'updateGroup',groupId:g.id,name:'x'},{action:'createRow',groupId:g.id,name:'x'},{action:'updateRow',rowId:row.id,name:'x'},{...block},{action:'deleteBlock',blockId:first.id},{action:'deleteRow',rowId:row.id},{action:'deleteGroup',groupId:g.id}])await call(data,'other',404);
 await Promise.all([call({...block,title:'Second'}),call({...block,title:'Third'})]);
 assert.equal((await call(week)).blocks.length,3);
 await call({...block,blockId:first.id,title:'Edited',end:'12:00'});
 assert.equal((await call(week)).blocks.find(b=>b.id===first.id).end,'12:00');
 await call({action:'deleteBlock',blockId:first.id});
 assert.equal((await call(week)).blocks.length,2);
 await call({action:'deleteRow',rowId:row.id});
 assert.equal((await call({...week,startDate:'2026-10-05'})).blocks.length,0);
  await call({action:'deleteGroup',groupId:g.id});assert.equal((await call(week)).groups.length,0);
  const {rowId,...hourly}=block;
  const standalone=(await call({...hourly,start:'23:00',end:'24:00'})).block;
  assert.equal(standalone.row_id,undefined);
  assert.equal((await call(week)).blocks[0].end,'24:00');
  await call({...hourly,start:'24:00',end:'24:00'},'owner',400);
  await call({...hourly,blockId:standalone.id},'other',404);
  await call({...hourly,blockId:standalone.id,start:'07:30',end:'08:30'});
  assert.equal((await call(week)).blocks[0].start,'07:30');
});
